# Generated by Django 4.1 on 2022-10-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("giftapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Giftmodel",),
    ]
