# Generated by Django 4.1 on 2022-10-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("giftapp", "0002_delete_giftmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Giftmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("giftname", models.CharField(max_length=100)),
                ("maxdate", models.DateField()),
                ("pinnum", models.IntegerField()),
                ("theme", models.CharField(max_length=100)),
                ("themeimg", models.CharField(max_length=100)),
            ],
            options={"db_table": "Giftmodel",},
        ),
    ]
