# Generated by Django 4.1 on 2022-10-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giftapp", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftmodel", name="maxdate", field=models.IntegerField(),
        ),
    ]
